
name: Python CI
  

on:
  push:
  pull_request:


jobs:
  lint-and-test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4


      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 


      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-python-


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest mypy pytest-cov
          pip install -r requirements.txt

      - name: Run Ruff Check
        run: |
          ruff check .
          ruff format --check . 
      

      - name: Run Unit Test
        run: pytest --cov=src tests

      - name: Run Type Check
        run: mypy src
